#!/bin/bash
if ! [ $CI40_CONFIG ]; then 
	export CI40_CONFIG=1
	export STAGING_DIR=/home/marcus/Documents/ci40_OS/openwrt_compiled/libcurl-lbxml2-openssl/staging_dir
	export TOOLCHAIN_DIR=$STAGING_DIR/toolchain-mipsel_mips32_gcc-5.2.0_musl-1.1.11
	export TARGET_DIR=$STAGING_DIR/target-mipsel_mips32_musl-1.1.11
	export LDCFLAGS=$TOOLCHAIN_DIR/usr/lib/
	export LD_LIBRARY_PATH=$TOOLCHAIN_DIR/usr/lib/
	export PATH=$TOOLCHAIN_DIR/bin/:$PATH
	export CROSS_LINKING_DIR=$TARGET_DIR/root-pistachio/usr/lib
fi

mipsel-openwrt-linux-g++ -static-libstdc++ -g -Wno-write-strings -I/home/marcus/Documents/ci40_OS/openwrt_compiled/libcurl-lbxml2-openssl/staging_dir/target-mipsel_mips32_musl-1.1.11/usr/include/ cURL_Test.cpp -o curlTest_ci40 -L/home/marcus/Documents/ci40_OS/openwrt_compiled/libcurl-lbxml2-openssl/staging_dir/target-mipsel_mips32_musl-1.1.11/usr/lib -lcurl -lpolarssl
