#!/bin/bash
if ! [ $CI40_CONFIG ]; then 
	export CI40_CONFIG=1
	export STAGING_DIR=/home/marcus/Documents/ci40_OS/openwrt_compiled/libcurl-lbxml2-openssl/staging_dir
	export TOOLCHAIN_DIR=$STAGING_DIR/toolchain-mipsel_mips32_gcc-5.2.0_musl-1.1.11
	export LDCFLAGS=$TOOLCHAIN_DIR/usr/lib/:$STAGING_DIR/target-mipsel_mips32_musl-1.1.11/usr/lib/
	export LD_LIBRARY_PATH=$TOOLCHAIN_DIR/usr/lib/:$STAGING_DIR/target-mipsel_mips32_musl-1.1.11/usr/lib/
	export PATH=$TOOLCHAIN_DIR/bin/:$PATH
fi

echo "SysRoot"
mipsel-openwrt-linux-g++ --with-sysroot -print-sysroot
echo "Search DIR:"
mipsel-openwrt-linux-g++ -print-search-dirs
