#!/bin/bash
if ! [ $CI40_CONFIG ]; then 
	export CI40_CONFIG=1
	export STAGING_DIR=/home/marcus/Documents/ci40_OS/openwrt_compiled/libcurl-openssl-chrony/staging_dir
	export TOOLCHAIN_DIR=$STAGING_DIR/toolchain-mipsel_mips32_gcc-5.2.0_musl-1.1.11
	export TARGET_DIR=$STAGING_DIR/target-mipsel_mips32_musl-1.1.11
	export LDCFLAGS=$TOOLCHAIN_DIR/usr/lib/
	export LD_LIBRARY_PATH=$TOOLCHAIN_DIR/usr/lib/
	export PATH=$TOOLCHAIN_DIR/bin/:$PATH
	export CROSS_LINKING_DIR=$TARGET_DIR/root-pistachio/usr/lib
fi

mipsel-openwrt-linux-g++ -static-libstdc++ -g -Wno-write-strings -std=c++11 -I/home/marcus/Documents/ci40_OS/openwrt_compiled/libcurl-openssl-chrony/staging_dir/target-mipsel_mips32_musl-1.1.11/usr/include/ ../CommandHandler.cpp ../Device.cpp ../Device_Socket.cpp ../DeviceManager.cpp ../Global.cpp ../HTTPRequest.cpp ../OutgoingCommandHandler.cpp ../Room.cpp ../RoomManager.cpp ../RoomDeviceMapManager.cpp ../UIDevice.cpp ../UIDeviceManager.cpp ../Util.cpp ../ThreadManager.cpp ../XMLUtil.cpp ../pugiXML/pugixml.cpp cleanup_TEST.cpp DeviceManager_TEST.cpp Device_TEST.cpp HTTPRequest_TEST.cpp RoomManager_TEST.cpp RoomDeviceMapManager_TEST.cpp UIDeviceManager_TEST.cpp main_TEST.cpp CommandHandler_TEST.cpp ThreadManager_TEST.cpp XML_TEST.cpp -o interHomeHubApp-ci40_test -L/home/marcus/Documents/ci40_OS/openwrt_compiled/libcurl-openssl-chrony/staging_dir/target-mipsel_mips32_musl-1.1.11/usr/lib -lcurl -lpolarssl -pthread