#!/bin/bash
if ! [ $CI40_CONFIG ]; then 
	export CI40_CONFIG=1
	export STAGING_DIR=/home/marcus/Documents/ci40_OS/openwrt/staging_dir/
	export TOOLCHAIN_DIR=$STAGING_DIR/toolchain-mipsel_mips32_gcc-5.2.0_musl-1.1.11/
	export LDCFLAGS=$TOOLCHAIN_DIR/usr/lib/
	export LD_LIBRARY_PATH=$TOOLCHAIN_DIR/usr/lib/
	export PATH=$TOOLCHAIN_DIR/bin/:$PATH
fi

mipsel-openwrt-linux-g++ -g -Wno-write-strings CommandHandler.cpp main.cpp Room.cpp RoomManager.cpp ./pugiXML/pugixml.cpp -o interHomeHubApp-ci40